### ISSUE TITLE
Implement simple link validity checker

### ISSUE THREAD

**Issue by Qubits01** [ltsdw/gofile-downloader#25]
Hi,

I have a longer list of link where several are dead.
The script errors out because it is creating accounts too fast.
It would be great to first check if a link is valid without account creation.

**Comment by ltsdw** [comment]
Hello there 😃 ,

Could you explain a bit more please, what is the error? Also could you provide examples so I can think of something?

Making a request to see if the link is down, to only then making an account, would result in 3 requests in total, instead of only 2, which would be much slower.

Also there's a simple check to see if the link is valid, it doesn't check if the files are down tho.
https://github.com/ltsdw/gofile-downloader/blob/8f239a658f8949cd766fa2c69f41d0616a194f9d/gofile-downloader.py#L48-L53

**Comment by Qubits01** [comment]
Hi, I have a .txt file with a gofile link in each line.
I use the following linux command to batch download:
`while read theline; do gofile-downloader.py "$theline"; done < links.txt`
This is the output I'm getting:
```
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/0GTLUl?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/1lOAYv?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/2OWO7C?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/3U49Y3?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/84tU2C?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/9iS8gT?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/Ah6VBM?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/BcHUxb?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Account creation failed!
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/CdCVUy?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/cna0O2?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
Starting, please wait...
Failed to get a link as response from the https://api.gofile.io/contents/F87QAF?wt=4fd6sg89d7s6&cache=true
Starting, please wait...
Account creation failed!
Starting, please wait...
Account creation failed!
```

**Comment by ltsdw** [comment]
hey, would you mind updating your script with the latest commits?

It doesn't do exactly what you asked for, but now you can simply pass your text files with the urls directly:

```
python gofile-downloader.py my-urls.txt
```

Also the account will be created only once so there's no need to spam the gofile's api with unnecessary requests anymore, I think it should fix your problem with the accounts failing to be created.

**Comment by Qubits01** [comment]
Hi,

thanks for the quick reaction. I can confirm that it now works perfectly - except that in line 261 the die method is called which terminates the whole program and thus also stops the batch processing. But it's an easy fix and I already did it for me.

**Comment by ltsdw** [comment]
Thanks for reporting it, it should be fixed by #27.

Any other problem please report 😄

**Comment by Qubits01** [comment]
Hi, I noticed another small issue.
It would be great, if the folder(s) would only be created when the link is valid. At the moment the folder(s) are always created .

**Comment by ltsdw** [comment]
Should be fixed by https://github.com/ltsdw/gofile-downloader/commit/015069ab8131a3845eb3c46fa20e06b0a923ef7c

Again, not what you asked for, as it doesn't directly check if it the link is valid or not, it only removes the root content directory if it's empty (which is the case when the link isn't valid anymore).

But if it has another directory in it, it won't remove the root directory even if its subdirectories are empty.
